- name: Test sudo
  command: whoami
  become: yes

- name: Upgrade apt cache and uprade packages
  apt: 
    update_cache: true
    upgrade: dist


- name: Install base packages
  apt:
    name: "{{ base_packages }}"
    state: present

- name: Enable and start UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow SSH
  ufw:
    rule: allow
    port: 22
    proto: tcp
  
- name: Install Nginx 
  apt: 
    name: nginx
    state: present
    update_cache: true

- name: Nginx reverse proxy
  template:
    src: voteapp.nginx.conf.j2
    dest: /etc/nginx/sites-available/voteapp
  notify:
    - restart nginx

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  when: ansible_facts.services['nginx.service'] is defined
  ignore_errors: true