- name: Setup Home Lab Base Config
  hosts: all
  become: true
  vars_files:
    - secret.yml
  roles: 
    - base

- name: Setup Home Lab Vote App
  hosts: all
  become: true
  vars_files:
    - secret.yml
  roles: 
    - voteapp

 