- name: Autostart prep
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon_reload: true
  loop: "{{critical_services}}"
  when: critical_services is defined and critical_services | length > 0 and
        item is defined and item + '.service' in ansible_facts.services and
        ansible_facts.services[item + '.service'] is defined
  ignore_errors: true
  tags: autostart

- name: Autostart config
  blockinfile:
    path: /etc/systemd/system/{{ safe_item }}.service
    create: true
    mode: '0644'
    block: |
      [Service]
      Restart=always
      RestartSec=5
      StartLimitInterval=0
  loop: "{{ critical_services }}"
  vars:
    safe_item: "{{ item | regex_replace('[^a-zA-Z0-9_.-]', '_') }}"
  when: item is defined and ansible_facts.services[item + '.service'] is not defined
  ignore_errors: true
  tags: autostart
  
- name: Config daemon_reload
  systemd:
    daemon_reload: true
  when: service_config.changed
  tags: autostart