---

- name: Gather service facts
  service_facts:
  tags: autostart

- name: Autostart prep
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon_reload: true
  loop: "{{ critical_services }}"
  when:
    - critical_services is defined
    - critical_services | length > 0
    - item is defined
    - (item + '.service') in ansible_facts.services
    - ansible_facts.services[item + '.service'] is defined
  ignore_errors: true
  tags: autostart

- name: Autostart config
  blockinfile:
    path: /etc/systemd/system/{{ safe_item }}.service
    create: true
    mode: '0644'
    block: |
      [Service]
      Restart=always
      RestartSec=5
      StartLimitInterval=0
  loop: "{{ critical_services }}"
  vars:
    safe_item: "{{ item | regex_replace('[^a-zA-Z0-9_.-]', '_') }}"
  when:
    - critical_services is defined
    - critical_services | length > 0
    - item is defined
    - (item + '.service') not in ansible_facts.services
  ignore_errors: true
  register: service_config
  tags: autostart

- name: Config daemon_reload
  systemd:
    daemon_reload: true
  when: service_config is changed
  tags: autostart
  